/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMyTripModal: typeof import('./src/components/layout/trip/AddMyTripModal.vue')['default']
    AddToGroupModal: typeof import('./src/components/layout/trip/AddToGroupModal.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppImage: typeof import('./src/components/common/AppImage.vue')['default']
    AppList: typeof import('./src/components/common/AppList.vue')['default']
    AppPagenation: typeof import('./src/components/common/AppPagenation.vue')['default']
    AppSearchBar: typeof import('./src/components/common/AppSearchBar.vue')['default']
    AppTable: typeof import('./src/components/common/AppTable.vue')['default']
    AppTabPane: typeof import('./src/components/common/AppTabPane.vue')['default']
    AttractionBucketlistContent: typeof import('./src/components/layout/map/attraction/AttractionBucketlistContent.vue')['default']
    AttractionDetailPane: typeof import('./src/components/layout/map/attraction/AttractionDetailPane.vue')['default']
    AttractionPane: typeof import('./src/components/layout/map/AttractionPane.vue')['default']
    AttractionSearchContent: typeof import('./src/components/layout/map/attraction/AttractionSearchContent.vue')['default']
    CommentOverlay: typeof import('./src/components/layout/feed/CommentOverlay.vue')['default']
    CommentPanel: typeof import('./src/components/layout/feed/CommentPanel.vue')['default']
    copy: typeof import('./src/components/layout/feed/FeedOverlay copy.vue')['default']
    FeedBoard: typeof import('./src/components/layout/feed/FeedBoard.vue')['default']
    FeedCard: typeof import('./src/components/layout/feed/FeedCard.vue')['default']
    FeedOverlay: typeof import('./src/components/layout/feed/FeedOverlay.vue')['default']
    FeedOverlayContent: typeof import('./src/components/layout/feed/FeedOverlayContent.vue')['default']
    FeedSidebar: typeof import('./src/components/layout/feed/FeedSidebar.vue')['default']
    FilterPane: typeof import('./src/components/layout/map/FilterPane.vue')['default']
    GroupListContent: typeof import('./src/components/layout/map/route/import/GroupListContent.vue')['default']
    IconMarker: typeof import('./src/components/layout/map/marker/IconMarker.vue')['default']
    ImageMarker: typeof import('./src/components/layout/map/marker/ImageMarker.vue')['default']
    Login: typeof import('./src/components/layout/auth/Login.vue')['default']
    MapView: typeof import('./src/components/layout/map/MapView.vue')['default']
    PlanCreateSlide: typeof import('./src/components/layout/map/route/PlanCreateSlide.vue')['default']
    PlanEditSlide: typeof import('./src/components/layout/map/route/PlanEditSlide.vue')['default']
    PlanTimeline: typeof import('./src/components/layout/trip/PlanTimeline.vue')['default']
    PolylineMarker: typeof import('./src/components/layout/map/marker/PolylineMarker.vue')['default']
    RouteImportDialog: typeof import('./src/components/layout/map/route/RouteImportDialog.vue')['default']
    RouteMakePane: typeof import('./src/components/layout/map/route/RouteMakePane.vue')['default']
    RoutePane: typeof import('./src/components/layout/map/RoutePane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteSaveDialog: typeof import('./src/components/layout/map/route/RouteSaveDialog.vue')['default']
    RouteViewImportDialog: typeof import('./src/components/layout/map/route/RouteViewImportDialog.vue')['default']
    RouteViewPane: typeof import('./src/components/layout/map/route/RouteViewPane.vue')['default']
    SignUp: typeof import('./src/components/layout/auth/SignUp.vue')['default']
    TripCard: typeof import('./src/components/layout/trip/TripCard.vue')['default']
    TripCreateSlide: typeof import('./src/components/layout/map/route/TripCreateSlide.vue')['default']
    TripEditSlide: typeof import('./src/components/layout/map/route/TripEditSlide.vue')['default']
    TripListContent: typeof import('./src/components/layout/map/route/import/TripListContent.vue')['default']
  }
}
