/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Feed/Board/BoardDetail': RouteRecordInfo<'/Feed/Board/BoardDetail', '/Feed/Board/BoardDetail', Record<never, never>, Record<never, never>>,
    '/Feed/Board/BoardEdit': RouteRecordInfo<'/Feed/Board/BoardEdit', '/Feed/Board/BoardEdit', Record<never, never>, Record<never, never>>,
    '/Feed/Board/BoardList': RouteRecordInfo<'/Feed/Board/BoardList', '/Feed/Board/BoardList', Record<never, never>, Record<never, never>>,
    '/Feed/Board/BoardSearch': RouteRecordInfo<'/Feed/Board/BoardSearch', '/Feed/Board/BoardSearch', Record<never, never>, Record<never, never>>,
    '/Feed/Board/BoardWrite': RouteRecordInfo<'/Feed/Board/BoardWrite', '/Feed/Board/BoardWrite', Record<never, never>, Record<never, never>>,
    '/Feed/Feed': RouteRecordInfo<'/Feed/Feed', '/Feed/Feed', Record<never, never>, Record<never, never>>,
    '/Group/GroupCreate': RouteRecordInfo<'/Group/GroupCreate', '/Group/GroupCreate', Record<never, never>, Record<never, never>>,
    '/Group/GroupDetail': RouteRecordInfo<'/Group/GroupDetail', '/Group/GroupDetail', Record<never, never>, Record<never, never>>,
    '/Group/GroupEdit': RouteRecordInfo<'/Group/GroupEdit', '/Group/GroupEdit', Record<never, never>, Record<never, never>>,
    '/Group/GroupList': RouteRecordInfo<'/Group/GroupList', '/Group/GroupList', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Map/Map': RouteRecordInfo<'/Map/Map', '/Map/Map', Record<never, never>, Record<never, never>>,
    '/Member/Auth': RouteRecordInfo<'/Member/Auth', '/Member/Auth', Record<never, never>, Record<never, never>>,
    '/Member/FindPassword': RouteRecordInfo<'/Member/FindPassword', '/Member/FindPassword', Record<never, never>, Record<never, never>>,
    '/Member/Logout': RouteRecordInfo<'/Member/Logout', '/Member/Logout', Record<never, never>, Record<never, never>>,
    '/Member/MemberDetail': RouteRecordInfo<'/Member/MemberDetail', '/Member/MemberDetail', Record<never, never>, Record<never, never>>,
    '/Member/MemberEdit': RouteRecordInfo<'/Member/MemberEdit', '/Member/MemberEdit', Record<never, never>, Record<never, never>>,
    '/Member/MemberTrips': RouteRecordInfo<'/Member/MemberTrips', '/Member/MemberTrips', Record<never, never>, Record<never, never>>,
    '/Support/Notice/NoticeDetail': RouteRecordInfo<'/Support/Notice/NoticeDetail', '/Support/Notice/NoticeDetail', Record<never, never>, Record<never, never>>,
    '/Support/Notice/NoticeEdit': RouteRecordInfo<'/Support/Notice/NoticeEdit', '/Support/Notice/NoticeEdit', Record<never, never>, Record<never, never>>,
    '/Support/Notice/NoticeList': RouteRecordInfo<'/Support/Notice/NoticeList', '/Support/Notice/NoticeList', Record<never, never>, Record<never, never>>,
    '/Support/Notice/NoticeWrite': RouteRecordInfo<'/Support/Notice/NoticeWrite', '/Support/Notice/NoticeWrite', Record<never, never>, Record<never, never>>,
    '/Support/Qna/QnaDetail': RouteRecordInfo<'/Support/Qna/QnaDetail', '/Support/Qna/QnaDetail', Record<never, never>, Record<never, never>>,
    '/Support/Qna/QnaEdit': RouteRecordInfo<'/Support/Qna/QnaEdit', '/Support/Qna/QnaEdit', Record<never, never>, Record<never, never>>,
    '/Support/Qna/QnaList': RouteRecordInfo<'/Support/Qna/QnaList', '/Support/Qna/QnaList', Record<never, never>, Record<never, never>>,
    '/Support/Qna/QnaWrite': RouteRecordInfo<'/Support/Qna/QnaWrite', '/Support/Qna/QnaWrite', Record<never, never>, Record<never, never>>,
    '/Support/Support': RouteRecordInfo<'/Support/Support', '/Support/Support', Record<never, never>, Record<never, never>>,
    '/Trip/TripDetail': RouteRecordInfo<'/Trip/TripDetail', '/Trip/TripDetail', Record<never, never>, Record<never, never>>,
    '/Trip/TripEdit': RouteRecordInfo<'/Trip/TripEdit', '/Trip/TripEdit', Record<never, never>, Record<never, never>>,
    '/Trip/TripList': RouteRecordInfo<'/Trip/TripList', '/Trip/TripList', Record<never, never>, Record<never, never>>,
    '/Trip/TripWrite': RouteRecordInfo<'/Trip/TripWrite', '/Trip/TripWrite', Record<never, never>, Record<never, never>>,
  }
}
